networks: 
  int_net:
  proxy_net:
  ext_net:
services: 
  mysql: 
    build: 
      context: "."
      dockerfile: mysql.Dockerfile
    environment: 
      - MYSQL_ROOT_PASSWORD=XMN347
      - MYSQL_DATABASE=dbkuasai
      - MYSQL_USER=cilsykuasaiuser
      - MYSQL_PASSWORD=cilsykuasaipassword
    image: wingky/mysql-custom
    networks: 
      - int_net
    volumes: 
      - "db-data:/var/lib/mysql"
  pma: 
    build: 
      context: "."
      dockerfile: pma.Dockerfile
    environment: 
      - PMA_HOST=mysql
    image: wingky/pma-custom
    networks: 
      - int_net
      - proxy_net
    #restart: always

  proxy: 
    build: 
      context: "."
      dockerfile: proxy.Dockerfile
    image: wingky/proxy-custom
    networks: 
      - proxy_net
      - ext_net
    volumes:
      - "proxy:/etc/nginx/conf.d/"
    ports: 
      - "80:80"

  web: 
    build: 
      context: "."
      dockerfile: webserver.Dockerfile
    image: wingky/web-custom
    networks: 
      - proxy_net
      - int_net
    volumes: 
      - "web:/var/www/html/"
version: "3.1"
volumes:
  web:
  db-data:
  proxy:
